### ISSUE TITLE
Get img from CDN

### ISSUE THREAD

**Issue by gary-deshayes** [WFCD/warframe-items#131]
Hello, i'm trying to display img of corpus enemy from your CDN, but when it try it, i'm redirect to another route https://raw.githubusercontent.com/wfcd/warframe-items/development/data/img/002-er.png instead of https://cdn.warframestat.us/img/002-er.png this give me nothing.

Anyone already have this issue ?

**Comment by TobiTenno** [comment]
the CDN redirects to the stored github image. the enemy images are missing right now due to some missing bits in the new parser that was rewritten a few months back. DE's newer storage area for the manifests doesn't include enemies anymore, so while we can add enemies to manually included, the images still may not exist.

**Comment by gary-deshayes** [comment]
Is there another way to retrieve all the images? I've seen the api content.warframe.com but I don't see how to use it.

**Comment by gary-deshayes** [comment]
Ok I see, thank you for your answers, I'll try to manage otherwise.

**Comment by TobiTenno** [comment]
If you find a way that we can build those images into this repo and keep them updated, let us know, it would be a big help!
