### ISSUE TITLE
Is there any data about components or armaments of RailJack?

### ISSUE THREAD

**Issue by NilToOne** [WFCD/warframe-items#178]
**Is your enhancement request related to a problem? Please describe.**
I'm a wiki editor from Fandom. If there are relevant data about components or armaments of RailJack, it will be easier to tabulate data according to json files instead of checking one by one in the game. And it is also good for some database websites.

**Describe the upgrade you'd like**
If there are relevant data about components or armaments of RailJack, you could add some information about where they are. You could write them down in README.md.

**Describe alternatives you've considered**
If there are not, but some repositories in github or other websites have, you could add some links.

**Additional context**
Thanks for listening.

**Comment by TobiTenno** [comment]
Hi, feel free to hop on our discord and we can discuss them a bit more. Railjack changes are a bit newer and not something we've had a look in at yet. 

We don't really link to other repos that have data, since we're trying to collate all data here.

Given that there's nothing (that I know of yet) in DE's mobile app. I'll take a look, but not seen anything yet, which is where we get our data.

**Comment by TobiTenno** [comment]
Looks like mods and skins got added, but nothing for things like turrets, armor, etc., yet

**Comment by TobiTenno** [comment]
I've found some railjack data, working to get it added
