### ISSUE TITLE
Inconsistent or incorrect data for exalted weapons

### ISSUE THREAD

**Issue by mechastrike** [WFCD/warframe-items#368]
### Describe the bug

Exalted weapons have inconsistent or incorrect damagePerShot, types, tags and others.

### NodeJS Version

v16.16.0

### npm Version

v8.16.0

### warframe-items Version

v1.1253.2595

### Access Method

npm Package (Default)

### What happened?

- All exalted weapons, including Necramech ones, and Garuda Talons are included in Misc.json which might be intentional but is very inconvenient when using all weapon data. Fetching over 600 items to use only 22 is pretty inefficient. But that might only be a me problem.
- Ironbride has the "Rifle" `type`.
- Only Artemis Bow and Arquebex have the `type` "Exalted Weapon" while the others have "Warframe". Including Artemis Bow Prime.
- Garuda Prime Talons have the value "Prime" while all the others have "Tenno" in `tags`. Except Ironbride and Arquebex which correctly have "Entrati".
- Artemis Bow, Artemis Bow Prime, Balefire Charger have 0 `damagePerShot` and `totalDamage`.
- Desert Wind, Dex Pixia, Dex Pixia Prime, Diwata, Diwata Prime, Exalted Blade, Exalted Prime Blade, Exalted Umbra Blade, Ironbride, Iron Staff, Iron Staff Prime, Shadow Claws, Valkyr Talons and Valkyr Prime `damagePerShot` values are inconsistent with the `attacks` values.
- Desert Wind, Ironbride, Valkyr Talons and Valkyr Prime Talons have an incorrect `procChance` value.
- Dex Pixia and Dex Pixia Prime have an incorrect `reloadTime` value. Arquebex, Balefire Charger, Regulators and Regulators Prime also have a `reloadTime` value despite never reloading but that's not a real issue.

Note that there might be more. I only provided the ones I currently work with.

**Comment by TobiTenno** [comment]
i'm gonna be kind here, and assume you don't know that most of the fields you just mentioned are generated by DE, in fact we don't generate any numeric fields apart from the disposition.

As for the "tags", those are configured by the wiki, so take that up with them.

For "type", those come from the unique id or from De themselves. Last I checked Ironbride is the primary, which is technically a rifle type for DE

**Comment by mechastrike** [comment]
I did not know. Thank you.
I will look into fixing the tags on the wiki. I might not be the first to try but doesn't hurt to try again.
I'm not sure what you mean about Ironbride being the primary but I understand it's out of your control.

**Comment by TobiTenno** [comment]
types are likely one of the few in our control, so that part we can probably fix. I can lay out some of the data sources by parts you mentioned:
- `type`: mostly us, from [this](https://github.com/WFCD/warframe-items/blob/master/config/itemTypes.json)
- `tags`: the `Traits` field in the lua files on the wiki
- `damagePerShot`, `totalDamage`, `reloadTime`, `procChance`: DE's raw data (fetched [here](https://github.com/WFCD/warframe-items/blob/master/build/scraper.js#L74))
- `attacks`: composite from the wiki's various "attack" objects, parsed [here](https://github.com/WFCD/warframe-items/blob/master/build/wikia/transformers/transformWeapon.js#L23-L63)

i think that covers all of them, but i'm open to working on the types as needed, since those are the ones i have some control over.
if "attacks" are wrong, my gut reaction is that wiki should be fixed to follow DE's app data, but it's just as likely that DE's app data is straight up wrong

**Comment by mechastrike** [comment]
I see. Thank you for the infos. That clears things up a lot.
I can see that managing `types` can be annoying when they add specific `uniqueName`s like Ironbride and its "AbilitySword/NechroTechSwordWeapon".
The `attacks` arrays have been reliable so far. It's usually the data from DE that have issues.
