### ISSUE TITLE
Add blueprint aquisition location for weapons and warframes

### ISSUE THREAD

**Issue by InfinitySamurai** [WFCD/warframe-items#42]
Currently, there is no information of where you can acquire blueprints for warframes or weapons unless they are prime's that need to be collected from relics. Could we add a field to these objects that has an enum stating where it can be acquired. E.g. "acquired": "relic", "acquired": "market", "acquired": "dojo (tenno)". This may clash with the fact that many items can be bought from the market for platinum regardless, however.

**Comment by Kaptard** [comment]
[The data endpoint for blueprints](http://content.warframe.com/MobileExport/Manifest/ExportRecipes.json) from DE doesn't include anything that could be used to determine item acquisition. 

We'd probably have to scrape this from the wikia which has a couple of keys indicating item acquisition (e.g. `lab = Tenno`). The issue is that as usual, the wikia is inconsistent and doesn't have this on everything. Especially blueprints acquired from the market have no such indicator, meaning we'd have to assume that by exclusion.

I'll have a look if this could actually be reasonably accurate.

**Comment by InfinitySamurai** [comment]
I feel like the Wiki and the API use should be the other way around. The Wiki should be using the API to display its data so that essentially the API is kept up to date while other places use the API as the source of information. 

Obviously, that's a much simpler thing to say than to implement. If you have any tasks around here that you need help with feel free to tag/contact me. Hell, I would almost be happy to go through and manually add that information to the endpoints myself

**Comment by TobiTenno** [comment]
That's what we'd like, overall, but some of the data isn't populated in DE's manifests, so we do what we can to add them. I can add a list of drop locations, basically just adding in the drops from https://drops.warframestat.us if needed. Would you be ok with that, @Kaptard?

**Comment by TobiTenno** [comment]
theoretically we could do overrides for stuff as needed, but that feels like a lot of effort for little gain.
i'd love if we had this populated and had a data-driven wiki for it, but we simply don't at present.
