### ISSUE TITLE
Relic rarity bug with radiant relics

### ISSUE THREAD

**Issue by droppedcode** [WFCD/warframe-items#55]
Issue:
Rarity for Radiant relics are uncommon for items that are rare.

Example:
{
            "location": "Meso E1 Flawless",
            "type": "Relics",
            "rarity": "Rare",
            "chance": 0.06
          },
          {
            "location": "Meso E1 Radiant",
            "type": "Relics",
            "rarity": "Uncommon",
            "chance": 0.1
          }

Note:
I have not checked all, but it happens all the cases I have checked.

**Comment by Kaptard** [comment]
I believe rarity, when in drop chances, refers to the rarity of the item drop for that relic. So since you're more likely to get the item you're looking for with Radiant relics than Flawless, they're changing the overall rarity indicator.

This is DE's weird classification of rarity, so there's nothing we can do about it. (See [official drop tables](http://n8k6e2y6.ssl.hwcdn.net/repos/hnfvc0o3jnfvc873njb03enrf56.html))
