### ISSUE TITLE
Add components for Warframes as separate items

### ISSUE THREAD

**Issue by will-janz** [WFCD/warframe-items#59]
The components for things like Neuroptics and Systems are not present. I checked the MobileExport manifest, and it has things like `AshChassisBlueprint` that list its requisite components. How feasible would it be to add those? 

Thank you!

**Comment by TobiTenno** [comment]
how deep are you wanting to go?

**Comment by will-janz** [comment]
I should've clarified; I would like to see a sort of Blueprints.json based off of [the API blueprints endpoint](http://content.warframe.com/MobileExport/Manifest/ExportRecipes.json). Trying to recursively add nested blueprints would bloat the dataset massively with tons of repeats. 

I've been perusing the source code and think I could, in some time, add this in a PR, but right now I want to get it on the radar.

**Comment by TobiTenno** [comment]
sure. if you have a chance and would like to, i'd love to see (and review) such a PR

**Comment by will-janz** [comment]
Will do! Holidays are upon us so I'm not sure when I'll have the time but it's on my list.

**Comment by Kaptard** [comment]
I've added the components inside components part in the `sanitizeComponents` method of parser.js, but it's commented out for now because it does bloat the output size. Just posting this in case anyone needs it urgently without a clean fix like an additional Blueprint.json

**Comment by TobiTenno** [comment]
i think having to check the items for the additional item is clean enough that it's safe to close this. cause at some point, it's going to get too deep to do without some runtime work...

**Comment by TobiTenno** [comment]
I think this makes more sense if we scope it differently:
Keeping components of something like warframes or weapons as separate components as well, otherwise the data we're looking for becomes lost, without it being redundantly saved.

**Comment by Xzandro** [comment]
We talked about this via Discord already and I totally agree here. We don't really need nesting when the data is already there. Warframe components are the only exception. I would suggest adding these to the Misc.json to keep the Warframes.json clean with only Warframes itself.

**Comment by Xzandro** [comment]
I further looked into this issue and the reason this is happening is that we don't process recipes in general. So normally this doesn't matter, since they will be applied to their respective parents. This is fine for most items like weapons.
As an example we have Akbolto. It doesn't really matter that we don't nest the Bolto data directly in there; you can always reference them, because they are items itself.

For Warframes (and more specific the components) this does not work, reason being they are not items, they are recipes, which have required components on their own. Since they are skipped in the process function and we don't go a second level, they are basically discarded and the component data is lost.

Imo here are two possibilities. Since they are both the same file size weise I'm more of a fan of the second one.

1. Make an exception in the process function and process Warframe Recipes. It now would be possible to add these to whatever type and category you want (Probably best place would be Misc, to keep the Warframe.json clean)
2. Make an exception in the sanitizeComponent function to autmcatically go a second level deep for Warframe components. I like this more, since all the data would be at the correct location and as I said, it wouldn't matter file wise. These components (and their data) are only related to their respective Warframe anyway

Either way is fine tho. Thoughts?

**Comment by TobiTenno** [comment]
Either shouldn't be terribly difficult, i'd prefer the first one.
